Repository jcaporossi/mnp-trufflebox, pull requests merged in 2022-01, with the labels that each got.

#3 Feature/roll dices
  client/src/components/Game.js
  client/src/components/User.js
  contracts/Board.sol
  test/Board.test.js
  test/BoardRandom.test.js
  truffle-config.js
Labels: to Test (include code review)

#4 Staking ERC20 + in Game entry
  .gitignore
  client/.gitignore
  client/public/images/tokens/eth.svg
  client/public/images/tokens/link.svg
  client/public/images/tokens/matic.svg
  client/public/images/tokens/mono.svg
  client/src/components/Admin.js
  client/src/components/App.js
  client/src/components/Game.js
  client/src/components/InGame.js
  client/src/components/Land.js
  client/src/components/Pool.js
  client/src/components/Staker.js
  client/src/components/User.js
  client/src/css/Staking.css
  contracts/Bank.sol
  contracts/Board.sol
  contracts/Local/EthUsdPriceFeed.sol
  contracts/Local/Link.sol
  contracts/Local/LinkForChainlinkVRF.sol
  contracts/Local/LinkUsdPriceFeed.sol
  contracts/Local/Matic.sol
  contracts/Local/MaticUsdPriceFeed.sol
  contracts/MonoUsdPriceFeed.sol
  contracts/Staking.sol
  contracts/Stubs/BuildStub.sol
  contracts/Stubs/ChainLinkPriceFeedStub.sol
  contracts/Stubs/ERC20TokenStub.sol
  contracts/Stubs/PawnStub.sol
  migrations/1_initial_migration.js
  migrations/2_contracts_migration.js
  test/Bank.test.js
  test/BankPropertyTransfer.test.js
  test/Board.test.js
  test/BoardRandom.test.js
  test/Build.test.js
  test/Prop.test.js
  test/PropertyRoyalties.test.js
  test/Staking.test.js
  truffle-config.js
Labels: to Test (include code review), to Merge

#6 fix some things in Game
  client/src/components/Game.js
  client/src/components/Land.js
  client/src/components/User.js
  client/src/data/Paris.json
  contracts/Bank.sol
  contracts/Board.sol
  migrations/2_contracts_migration.js
Labels: to Merge

#7 fix retrieving prices
  client/src/components/Land.js
Labels: to Merge

#8 Feature/polygon migration
  contracts/Bank.sol
  contracts/Board.sol
  contracts/Prop.sol
  migrations/2_contracts_migration.js
  truffle-config.js
Labels: to Test (include code review), to Merge

#9 Front improvment and add VRF Coordinator contract to simulate better …
  DEPLOYED_ADDRESSES.md
  DESIGN_PATTERN_DECISIONS.md
  README.md
  client/public/images/tokens/mono-symbol.svg
  client/public/images/tokens/mono.svg
  client/src/assets/dices_shaker.gif
  client/src/assets/mono-symbol.svg
  client/src/components/Admin.js
  client/src/components/App.js
  client/src/components/Game.js
  client/src/components/Grid.js
  client/src/components/Land.js
  client/src/components/Pool.js
  client/src/components/Staker.js
  client/src/components/User.js
  client/src/components/Visual.js
  client/src/css/Staking.css
  client/src/css/User.css
  client/src/data/Paris.json
  contracts/Bank.sol
  contracts/Board.sol
  contracts/Build.sol
  contracts/Local/LinkForChainlinkVRF.sol
  contracts/Local/VRFCoordinator.sol
  contracts/Prop.sol
  contracts/Stubs/BoardMock.sol
  contracts/Stubs/BoardStub.sol
  contracts/Stubs/BuildStub.sol
  contracts/Stubs/PawnStub.sol
  migrations/1_initial_migration.js
  migrations/2_contracts_migration.js
  test/Bank#propertyTransfer.test.js
  test/Bank.test.js
  test/Board.Random.test.js
  test/Board.test.js
  test/BoardRandom.test.js
  test/Build.test.js
  test/Prop.PropertyRoyalties.test.js
  test/Prop.test.js
  test/TESTS_EXPLICATION.md
  truffle-config.js
Labels: to Test (include code review)

#13 Fix/some bugs
  DEPLOYED_ADDRESSES.md
  README.md
  client/public/favicon.ico
  client/public/fonts/ITCKabelStdBold.woff
  client/public/fonts/ITCKabelStdBook.woff
  client/public/fonts/ITCKabelStdDemi.woff
  client/public/fonts/ITCKabelStdMedium.woff
  client/public/fonts/ITCKabelStdUltra.woff
  client/public/fonts/MONOPOLY_INLINE.woff
  client/public/index.css
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/src/assets/dice_face_1.png
  client/src/assets/dice_face_2.png
  client/src/assets/dice_face_3.png
  client/src/assets/dice_face_4.png
  client/src/assets/dice_face_5.png
  client/src/assets/dice_face_6.png
  client/src/assets/dices/dice_face_1.png
  client/src/assets/dices/dice_face_2.png
  client/src/assets/dices/dice_face_3.png
  client/src/assets/dices/dice_face_4.png
  client/src/assets/dices/dice_face_5.png
  client/src/assets/dices/dice_face_6.png
  client/src/components/App.js
  client/src/components/Game.js
  client/src/components/Grid.js
  client/src/components/InGame.js
  client/src/components/Land.js
  client/src/components/Rules.js
  client/src/components/User.js
  client/src/components/Visual.js
  client/src/css/App.css
  client/src/css/Game.css
  client/src/css/Grid.css
  client/src/css/Staking.css
  client/src/css/User.css
  client/src/data/Paris.json
  client/src/index.css
  contracts/Bank.sol
  contracts/Board.sol
  contracts/withGanacheOnly/EthUsdPriceFeed.sol
  contracts/withGanacheOnly/Link.sol
  contracts/withGanacheOnly/LinkForChainlinkVRF.sol
  contracts/withGanacheOnly/LinkUsdPriceFeed.sol
  contracts/withGanacheOnly/Matic.sol
  contracts/withGanacheOnly/MaticUsdPriceFeed.sol
  contracts/withGanacheOnly/VRFCoordinator.sol
  migrations/2_contracts_migration.js
  package-lock.json
  package.json
  test/Board.test.js
  truffle-config.js
Labels: in Progress, to Merge

#16 initiate 3d rolling
  DEPLOYED_ADDRESSES.md
  client/package-lock.json
  client/package.json
  client/public/images/tokens/matic-mono.png
  client/public/images/tokens/mono.png
  client/src/components/App.js
  client/src/components/App.local.js
  client/src/components/DiceBoard/Dice.js
  client/src/components/DiceBoard/DiceBoard.js
  client/src/components/DiceBoard/OrbitControls.js
  client/src/components/Game.js
  client/src/components/Pool.js
  client/src/components/Staker.js
  client/src/components/User.js
  client/src/components/Visual.js
  client/src/css/Game.css
  contracts/Bank.sol
  contracts/Staking.sol
  contracts/notUsedInProduction/MaticMono.sol
  contracts/notUsedInProduction/MaticMonoPriceFeed.sol
  migrations/2_contracts_migration.js
  package-lock.json
  package.json
  test/Board.Random.test.js
  test/Staking.test.js
Labels: in Progress
